version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - \"8000:8000\"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: .
    ports:
      - \"3000:3000\"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped