python = "3.9"

[phases.build]
cmds = [
  "pip install -r requirements.txt"
]

[phases.setup]
nixPkgs = ["ffmpeg"]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"

[variables]
PYTHONPATH = "./backend"